ervices:
  swiftros2_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - HOST_UID=${UID:-1000}
        - HOST_GID=${GID:-1000}
        - USERNAME=${USER:-$(id -un)}
    image: localhost/swiftros2_dev:latest
    container_name: swiftros2_dev
    network_mode: "host"
    userns_mode: "keep-id"
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - /home/jack/dev/smithjack.net/SwiftRos2:/swiftros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    devices:
      - /dev/ttyACM0:/dev/ttyACM0      
 
